### ISSUE TITLE
Run error

### ISSUE THREAD

**Issue by ZhimingShi** [MaodongGao/pycosh#1]
Hello！I always get the following error when I run this code to calculate laser frequency noise, how can I get rid of this error?
![image](https://github.com/MaodongGao/pycosh/assets/121110294/81ecc0ff-5272-4204-aa9c-2965e0686423)

![image](https://github.com/MaodongGao/pycosh/assets/121110294/452181f0-c3ce-48c6-8658-0de1b582415f)

**Comment by MaodongGao** [comment]
Hi Zhiming,

It looks like the processing time it reported is very short. What is the size of your raw data?

________________________________
From: ZhimingShi ***@***.***>
Sent: Thursday, April 18, 2024 9:08:13 AM
To: MaodongGao/pycosh ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [MaodongGao/pycosh] Run error (Issue #1)


Hello！I always get the following error when I run this code to calculate laser frequency noise, how can I get rid of this error?
image.png (view on web)<https://github.com/MaodongGao/pycosh/assets/121110294/81ecc0ff-5272-4204-aa9c-2965e0686423>

image.png (view on web)<https://github.com/MaodongGao/pycosh/assets/121110294/452181f0-c3ce-48c6-8658-0de1b582415f>

**Comment by ZhimingShi** [comment]
Hello! Thank you very much for your reply. The very short time is because I tested this code with very small raw data, and now I've increased the data a lot, with a sampling rate of 250MHz/s, and an AOM frequency of 55MHz, and then a sampling time of 0.4ms. I ran this re-captured data, and it's still reporting the same error as before. I read the literature on Optics Express carefully. The parameter settings in CoshConfig.py are basically the same as in the literature, this range_start, range_stop and offset_start_ratio I have not changed, is it possible that I need to change them here depending on the amount of data I have?
![image](https://github.com/MaodongGao/pycosh/assets/121110294/5da63e31-4bf9-4ab5-9f78-b9ccd5c41747)
Can you give me your email address, I would like to show you the data and processing code to find out the reason for this error. I think the test method for laser phase noise on this article is very good, I would appreciate it if you could reply.
![image](https://github.com/MaodongGao/pycosh/assets/121110294/6db218ef-94f8-405b-988e-ed0eef06c423)
![image](https://github.com/MaodongGao/pycosh/assets/121110294/d8167e0f-ac26-4753-b178-a79a9dd31bf9)

**Comment by MaodongGao** [comment]
Hi Zhiming,

One thing I am worried about is the segment count it is reporting are always 0. The correct behavior should not be like this. This parameter means for this bandwidth segment, how many data slices are involved. You can see details in CoshXcorr.py line 69.


Given the behavior you described, I recommend try to run the following code:

`np.mod(np.diff(np.angle(scipy.signal.hilbert(YOURDATA - np.mean(YOURDATA)))), 2 * np.pi)`

And see if the phase is correctly calculated. Let me know what you get, Thanks.

Maodong

**Comment by MaodongGao** [comment]
Hi Zhiming,

I realized another thing: your data 250MHz, 0.4ms only contains 1e5 data point. You can not calculate low-bandwidth data in this case. In order to calculate low bandwidth data you need to increase your sampling time.

You can see from the debug info: some segment_length is even more than total num of points you have, for those cases it is not surprising you see a failed processing.

The subsequent failure is probably the phase change data is erased when it tries to reshape to a segment_count=0 dimension array.

Try:

  1.  Delete the low bandwidth components in bandwidth segment. (self.config.bw_segment)
  2.  Increase offset_start_ratio
  3.  Make sure the segment length you see is smaller than total data length you have.
  4.  Ultimately, you may want to increase your data collection time. In our experiment, we typically take data for 1-2 seconds.

Maodong

**Comment by MaodongGao** [comment]
A typo: 2. Increase offset_start_ratio

Maodong Gao|Graduate Student

Department of Applied Physics Caltech
On Apr 18, 2024 at 8:40 PM -0700, Gao, Maodong ***@***.***>, wrote:
Hi Zhiming,

I realized another thing: your data 250MHz, 0.4ms only contains 1e5 data point. You can not calculate low-bandwidth data in this case. In order to calculate low bandwidth data you need to increase your sampling time.

You can see from the debug info: some segment_length is even more than total num of points you have, for those cases it is not surprising you see a failed processing.

The subsequent failure is probably the phase change data is erased when it tries to reshape to a segment_count=0 dimension array.

Try:

  1.  Delete the low bandwidth components in bandwidth segment. (self.config.bw_segment)
  2.  Decrease offset_start_ratio
  3.  Make sure the segment length you see is smaller than total data length you have.
  4.  Ultimately, you may want to increase your data collection time. In our experiment, we typically take data for 1-2 seconds.

Maodong

Maodong Gao|Graduate Student

Department of Applied Physics Caltech
On Apr 18, 2024 at 8:11 PM -0700, ZhimingShi ***@***.***>, wrote:

Hello! Thank you very much for your reply. The very short time is because I tested this code with very small raw data, and now I've increased the data a lot, with a sampling rate of 250MHz/s, and an AOM frequency of 55MHz, and then a sampling time of 0.4ms. I ran this re-captured data, and it's still reporting the same error as before. I read the literature on Optics Express carefully. The parameter settings in CoshConfig.py are basically the same as in the literature, this range_start, range_stop and offset_start_ratio I have not changed, is it possible that I need to change them here depending on the amount of data I have?
image.png (view on web)<https://github.com/MaodongGao/pycosh/assets/121110294/5da63e31-4bf9-4ab5-9f78-b9ccd5c41747>
Can you give me your email address, I would like to show you the data and processing code to find out the reason for this error. I think the test method for laser phase noise on this article is very good, I would appreciate it if you could reply.
image.png (view on web)<https://github.com/MaodongGao/pycosh/assets/121110294/6db218ef-94f8-405b-988e-ed0eef06c423>
image.png (view on web)<https://github.com/MaodongGao/pycosh/assets/121110294/d8167e0f-ac26-4753-b178-a79a9dd31bf9>

**Comment by ZhimingShi** [comment]
Sorry, my previous expression was wrong, the sampling time is 0.4s not 0.4ms. Each channel has 100*1e6 points of data. 
 run the following code: `np.mod(np.diff(np.angle(scipy.signal.hilbert(YOURDATA - np.mean(YOURDATA)))), 2 * np.pi)`
![image](https://github.com/MaodongGao/pycosh/assets/121110294/eb7fa5a5-af00-4681-ba93-b399b0e4999e)
![image](https://github.com/MaodongGao/pycosh/assets/121110294/7886bbb0-5ae6-4aaa-86ec-1e43ba5d800e)

I have modified the bandwidth segment and offset_start_ratio as follows
![image](https://github.com/MaodongGao/pycosh/assets/121110294/1d7ff459-bf98-49df-81d4-c6ddc67b8c2c)

But the result of running is still wrong.
![image](https://github.com/MaodongGao/pycosh/assets/121110294/bc5117a9-66c4-4775-a00b-16bbc83f6c98)

**Comment by kester2015** [comment]
Your data is a list of list, not a n*1 list. You may need to add

`data1 = data1[0]`
`data2 = data2[0]`

Let me know if this solved your problem.

Additionally, you are not supposed to modify the default configuration parameters directly in the source code. Doing this may cause unexpected behavior in the future. Modify your configurations by:

`xcorr_obj = CoshXcorr(data1, data2)`
`xcorr_obj.config.bw_sement = [......]`

Other parameters you can modify are all listed in the debug info printed unser "Cosh configuration summary"

**Comment by MaodongGao** [comment]
Your data is a 1* 1 list of list, not a n*1 list of raw data. You may need to add

`data1 = data1[0]`
`data2 = data2[0]`

Let me know if this solved your problem.

Additionally, you are not supposed to modify the default configuration parameters directly in the source code. Doing this may cause unexpected behavior in the future. Modify your configurations by:

`xcorr_obj = CoshXcorr(data1, data2)`
`xcorr_obj.config.bw_segment = YOUR CONFIGURATIONS HERE`

Other parameters you can modify are all listed in the debug info printed under "Cosh configuration summary"

**Comment by ZhimingShi** [comment]
Well, it ran successfully without any errors, thank you very much for your patience！
![image](https://github.com/MaodongGao/pycosh/assets/121110294/b4e962ca-288b-4e7f-9b5d-de8e7b1dc7b0)
